package com.inverse.ing;
// Generated 09/05/2017 03:21:15 PM by Hibernate Tools 4.0.1.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AreadepericiaId generated by hbm2java
 */
@Embeddable
public class AreadepericiaId  implements java.io.Serializable {


     private String descripcion;
     private Character estatus;
     private int codigoarea;

    public AreadepericiaId() {
    }

	
    public AreadepericiaId(int codigoarea) {
        this.codigoarea = codigoarea;
    }
    public AreadepericiaId(String descripcion, Character estatus, int codigoarea) {
       this.descripcion = descripcion;
       this.estatus = estatus;
       this.codigoarea = codigoarea;
    }
   


    @Column(name="descripcion")
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }


    @Column(name="estatus", length=1)
    public Character getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(Character estatus) {
        this.estatus = estatus;
    }


    @Column(name="codigoarea", nullable=false)
    public int getCodigoarea() {
        return this.codigoarea;
    }
    
    public void setCodigoarea(int codigoarea) {
        this.codigoarea = codigoarea;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AreadepericiaId) ) return false;
		 AreadepericiaId castOther = ( AreadepericiaId ) other; 
         
		 return ( (this.getDescripcion()==castOther.getDescripcion()) || ( this.getDescripcion()!=null && castOther.getDescripcion()!=null && this.getDescripcion().equals(castOther.getDescripcion()) ) )
 && ( (this.getEstatus()==castOther.getEstatus()) || ( this.getEstatus()!=null && castOther.getEstatus()!=null && this.getEstatus().equals(castOther.getEstatus()) ) )
 && (this.getCodigoarea()==castOther.getCodigoarea());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDescripcion() == null ? 0 : this.getDescripcion().hashCode() );
         result = 37 * result + ( getEstatus() == null ? 0 : this.getEstatus().hashCode() );
         result = 37 * result + this.getCodigoarea();
         return result;
   }   


}


