package com.inverse.ing;
// Generated 09/05/2017 03:21:15 PM by Hibernate Tools 4.0.1.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CategoriasporideaId generated by hbm2java
 */
@Embeddable
public class CategoriasporideaId  implements java.io.Serializable {


     private Integer idIdea;
     private Integer idCategoria;

    public CategoriasporideaId() {
    }

    public CategoriasporideaId(Integer idIdea, Integer idCategoria) {
       this.idIdea = idIdea;
       this.idCategoria = idCategoria;
    }
   


    @Column(name="id_idea")
    public Integer getIdIdea() {
        return this.idIdea;
    }
    
    public void setIdIdea(Integer idIdea) {
        this.idIdea = idIdea;
    }


    @Column(name="id_categoria")
    public Integer getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(Integer idCategoria) {
        this.idCategoria = idCategoria;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CategoriasporideaId) ) return false;
		 CategoriasporideaId castOther = ( CategoriasporideaId ) other; 
         
		 return ( (this.getIdIdea()==castOther.getIdIdea()) || ( this.getIdIdea()!=null && castOther.getIdIdea()!=null && this.getIdIdea().equals(castOther.getIdIdea()) ) )
 && ( (this.getIdCategoria()==castOther.getIdCategoria()) || ( this.getIdCategoria()!=null && castOther.getIdCategoria()!=null && this.getIdCategoria().equals(castOther.getIdCategoria()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdIdea() == null ? 0 : this.getIdIdea().hashCode() );
         result = 37 * result + ( getIdCategoria() == null ? 0 : this.getIdCategoria().hashCode() );
         return result;
   }   


}


