package com.inverse.ing;
// Generated 09/05/2017 03:21:15 PM by Hibernate Tools 4.0.1.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EvaluadoresdesafioId generated by hbm2java
 */
@Embeddable
public class EvaluadoresdesafioId  implements java.io.Serializable {


     private String evaluador;
     private Integer iddesafio;

    public EvaluadoresdesafioId() {
    }

    public EvaluadoresdesafioId(String evaluador, Integer iddesafio) {
       this.evaluador = evaluador;
       this.iddesafio = iddesafio;
    }
   


    @Column(name="evaluador")
    public String getEvaluador() {
        return this.evaluador;
    }
    
    public void setEvaluador(String evaluador) {
        this.evaluador = evaluador;
    }


    @Column(name="iddesafio")
    public Integer getIddesafio() {
        return this.iddesafio;
    }
    
    public void setIddesafio(Integer iddesafio) {
        this.iddesafio = iddesafio;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EvaluadoresdesafioId) ) return false;
		 EvaluadoresdesafioId castOther = ( EvaluadoresdesafioId ) other; 
         
		 return ( (this.getEvaluador()==castOther.getEvaluador()) || ( this.getEvaluador()!=null && castOther.getEvaluador()!=null && this.getEvaluador().equals(castOther.getEvaluador()) ) )
 && ( (this.getIddesafio()==castOther.getIddesafio()) || ( this.getIddesafio()!=null && castOther.getIddesafio()!=null && this.getIddesafio().equals(castOther.getIddesafio()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEvaluador() == null ? 0 : this.getEvaluador().hashCode() );
         result = 37 * result + ( getIddesafio() == null ? 0 : this.getIddesafio().hashCode() );
         return result;
   }   


}


