package com.inverse.ing;
// Generated 09/05/2017 03:21:15 PM by Hibernate Tools 4.0.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Evaluacion generated by hbm2java
 */
@Entity
@Table(name="evaluacion"
    ,schema="public"
)
public class Evaluacion  implements java.io.Serializable {


     private EvaluacionId id;

    public Evaluacion() {
    }

    public Evaluacion(EvaluacionId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="evaluadorUsername", column=@Column(name="evaluador_username") ), 
        @AttributeOverride(name="impacto", column=@Column(name="impacto") ), 
        @AttributeOverride(name="factibilidad", column=@Column(name="factibilidad") ), 
        @AttributeOverride(name="detalle", column=@Column(name="detalle") ), 
        @AttributeOverride(name="fecha", column=@Column(name="fecha", length=13) ), 
        @AttributeOverride(name="codigoIdea", column=@Column(name="codigo_idea") ) } )
    public EvaluacionId getId() {
        return this.id;
    }
    
    public void setId(EvaluacionId id) {
        this.id = id;
    }




}


