package com.inverse.ing;
// Generated 09/05/2017 03:21:15 PM by Hibernate Tools 4.0.1.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EvaluacionId generated by hbm2java
 */
@Embeddable
public class EvaluacionId  implements java.io.Serializable {


     private String evaluadorUsername;
     private Integer impacto;
     private Integer factibilidad;
     private String detalle;
     private Date fecha;
     private Integer codigoIdea;

    public EvaluacionId() {
    }

    public EvaluacionId(String evaluadorUsername, Integer impacto, Integer factibilidad, String detalle, Date fecha, Integer codigoIdea) {
       this.evaluadorUsername = evaluadorUsername;
       this.impacto = impacto;
       this.factibilidad = factibilidad;
       this.detalle = detalle;
       this.fecha = fecha;
       this.codigoIdea = codigoIdea;
    }
   


    @Column(name="evaluador_username")
    public String getEvaluadorUsername() {
        return this.evaluadorUsername;
    }
    
    public void setEvaluadorUsername(String evaluadorUsername) {
        this.evaluadorUsername = evaluadorUsername;
    }


    @Column(name="impacto")
    public Integer getImpacto() {
        return this.impacto;
    }
    
    public void setImpacto(Integer impacto) {
        this.impacto = impacto;
    }


    @Column(name="factibilidad")
    public Integer getFactibilidad() {
        return this.factibilidad;
    }
    
    public void setFactibilidad(Integer factibilidad) {
        this.factibilidad = factibilidad;
    }


    @Column(name="detalle")
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }


    @Column(name="fecha", length=13)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }


    @Column(name="codigo_idea")
    public Integer getCodigoIdea() {
        return this.codigoIdea;
    }
    
    public void setCodigoIdea(Integer codigoIdea) {
        this.codigoIdea = codigoIdea;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EvaluacionId) ) return false;
		 EvaluacionId castOther = ( EvaluacionId ) other; 
         
		 return ( (this.getEvaluadorUsername()==castOther.getEvaluadorUsername()) || ( this.getEvaluadorUsername()!=null && castOther.getEvaluadorUsername()!=null && this.getEvaluadorUsername().equals(castOther.getEvaluadorUsername()) ) )
 && ( (this.getImpacto()==castOther.getImpacto()) || ( this.getImpacto()!=null && castOther.getImpacto()!=null && this.getImpacto().equals(castOther.getImpacto()) ) )
 && ( (this.getFactibilidad()==castOther.getFactibilidad()) || ( this.getFactibilidad()!=null && castOther.getFactibilidad()!=null && this.getFactibilidad().equals(castOther.getFactibilidad()) ) )
 && ( (this.getDetalle()==castOther.getDetalle()) || ( this.getDetalle()!=null && castOther.getDetalle()!=null && this.getDetalle().equals(castOther.getDetalle()) ) )
 && ( (this.getFecha()==castOther.getFecha()) || ( this.getFecha()!=null && castOther.getFecha()!=null && this.getFecha().equals(castOther.getFecha()) ) )
 && ( (this.getCodigoIdea()==castOther.getCodigoIdea()) || ( this.getCodigoIdea()!=null && castOther.getCodigoIdea()!=null && this.getCodigoIdea().equals(castOther.getCodigoIdea()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEvaluadorUsername() == null ? 0 : this.getEvaluadorUsername().hashCode() );
         result = 37 * result + ( getImpacto() == null ? 0 : this.getImpacto().hashCode() );
         result = 37 * result + ( getFactibilidad() == null ? 0 : this.getFactibilidad().hashCode() );
         result = 37 * result + ( getDetalle() == null ? 0 : this.getDetalle().hashCode() );
         result = 37 * result + ( getFecha() == null ? 0 : this.getFecha().hashCode() );
         result = 37 * result + ( getCodigoIdea() == null ? 0 : this.getCodigoIdea().hashCode() );
         return result;
   }   


}


