package com.inverse.ing;
// Generated 09/05/2017 03:21:15 PM by Hibernate Tools 4.0.1.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrganizacionId generated by hbm2java
 */
@Embeddable
public class OrganizacionId  implements java.io.Serializable {


     private String rif;
     private String razonsocial;
     private String direccion;
     private String telefono;
     private Boolean sucursal;
     private String rifmatriz;
     private String nombre;

    public OrganizacionId() {
    }

    public OrganizacionId(String rif, String razonsocial, String direccion, String telefono, Boolean sucursal, String rifmatriz, String nombre) {
       this.rif = rif;
       this.razonsocial = razonsocial;
       this.direccion = direccion;
       this.telefono = telefono;
       this.sucursal = sucursal;
       this.rifmatriz = rifmatriz;
       this.nombre = nombre;
    }
   


    @Column(name="rif")
    public String getRif() {
        return this.rif;
    }
    
    public void setRif(String rif) {
        this.rif = rif;
    }


    @Column(name="razonsocial")
    public String getRazonsocial() {
        return this.razonsocial;
    }
    
    public void setRazonsocial(String razonsocial) {
        this.razonsocial = razonsocial;
    }


    @Column(name="direccion")
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }


    @Column(name="telefono")
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }


    @Column(name="sucursal")
    public Boolean getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(Boolean sucursal) {
        this.sucursal = sucursal;
    }


    @Column(name="rifmatriz")
    public String getRifmatriz() {
        return this.rifmatriz;
    }
    
    public void setRifmatriz(String rifmatriz) {
        this.rifmatriz = rifmatriz;
    }


    @Column(name="nombre")
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrganizacionId) ) return false;
		 OrganizacionId castOther = ( OrganizacionId ) other; 
         
		 return ( (this.getRif()==castOther.getRif()) || ( this.getRif()!=null && castOther.getRif()!=null && this.getRif().equals(castOther.getRif()) ) )
 && ( (this.getRazonsocial()==castOther.getRazonsocial()) || ( this.getRazonsocial()!=null && castOther.getRazonsocial()!=null && this.getRazonsocial().equals(castOther.getRazonsocial()) ) )
 && ( (this.getDireccion()==castOther.getDireccion()) || ( this.getDireccion()!=null && castOther.getDireccion()!=null && this.getDireccion().equals(castOther.getDireccion()) ) )
 && ( (this.getTelefono()==castOther.getTelefono()) || ( this.getTelefono()!=null && castOther.getTelefono()!=null && this.getTelefono().equals(castOther.getTelefono()) ) )
 && ( (this.getSucursal()==castOther.getSucursal()) || ( this.getSucursal()!=null && castOther.getSucursal()!=null && this.getSucursal().equals(castOther.getSucursal()) ) )
 && ( (this.getRifmatriz()==castOther.getRifmatriz()) || ( this.getRifmatriz()!=null && castOther.getRifmatriz()!=null && this.getRifmatriz().equals(castOther.getRifmatriz()) ) )
 && ( (this.getNombre()==castOther.getNombre()) || ( this.getNombre()!=null && castOther.getNombre()!=null && this.getNombre().equals(castOther.getNombre()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRif() == null ? 0 : this.getRif().hashCode() );
         result = 37 * result + ( getRazonsocial() == null ? 0 : this.getRazonsocial().hashCode() );
         result = 37 * result + ( getDireccion() == null ? 0 : this.getDireccion().hashCode() );
         result = 37 * result + ( getTelefono() == null ? 0 : this.getTelefono().hashCode() );
         result = 37 * result + ( getSucursal() == null ? 0 : this.getSucursal().hashCode() );
         result = 37 * result + ( getRifmatriz() == null ? 0 : this.getRifmatriz().hashCode() );
         result = 37 * result + ( getNombre() == null ? 0 : this.getNombre().hashCode() );
         return result;
   }   


}


