package com.inverse.ing;
// Generated 09/05/2017 03:21:15 PM by Hibernate Tools 4.0.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Areadepericia generated by hbm2java
 */
@Entity
@Table(name="areadepericia"
    ,schema="public"
)
public class Areadepericia  implements java.io.Serializable {


     private AreadepericiaId id;

    public Areadepericia() {
    }

    public Areadepericia(AreadepericiaId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="descripcion", column=@Column(name="descripcion") ), 
        @AttributeOverride(name="estatus", column=@Column(name="estatus", length=1) ), 
        @AttributeOverride(name="codigoarea", column=@Column(name="codigoarea", nullable=false) ) } )
    public AreadepericiaId getId() {
        return this.id;
    }
    
    public void setId(AreadepericiaId id) {
        this.id = id;
    }




}


