package com.inverse.ing;
// Generated 09/05/2017 03:21:15 PM by Hibernate Tools 4.0.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Areaestrategica generated by hbm2java
 */
@Entity
@Table(name="areaestrategica"
    ,schema="public"
)
public class Areaestrategica  implements java.io.Serializable {


     private AreaestrategicaId id;

    public Areaestrategica() {
    }

    public Areaestrategica(AreaestrategicaId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="descripcion", column=@Column(name="descripcion") ), 
        @AttributeOverride(name="estatus", column=@Column(name="estatus") ), 
        @AttributeOverride(name="codareaest", column=@Column(name="codareaest", nullable=false) ) } )
    public AreaestrategicaId getId() {
        return this.id;
    }
    
    public void setId(AreaestrategicaId id) {
        this.id = id;
    }




}


