package com.inverse.ing;
// Generated 09/05/2017 03:21:15 PM by Hibernate Tools 4.0.1.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AreaestrategicaId generated by hbm2java
 */
@Embeddable
public class AreaestrategicaId  implements java.io.Serializable {


     private String descripcion;
     private String estatus;
     private int codareaest;

    public AreaestrategicaId() {
    }

	
    public AreaestrategicaId(int codareaest) {
        this.codareaest = codareaest;
    }
    public AreaestrategicaId(String descripcion, String estatus, int codareaest) {
       this.descripcion = descripcion;
       this.estatus = estatus;
       this.codareaest = codareaest;
    }
   


    @Column(name="descripcion")
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }


    @Column(name="estatus")
    public String getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }


    @Column(name="codareaest", nullable=false)
    public int getCodareaest() {
        return this.codareaest;
    }
    
    public void setCodareaest(int codareaest) {
        this.codareaest = codareaest;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AreaestrategicaId) ) return false;
		 AreaestrategicaId castOther = ( AreaestrategicaId ) other; 
         
		 return ( (this.getDescripcion()==castOther.getDescripcion()) || ( this.getDescripcion()!=null && castOther.getDescripcion()!=null && this.getDescripcion().equals(castOther.getDescripcion()) ) )
 && ( (this.getEstatus()==castOther.getEstatus()) || ( this.getEstatus()!=null && castOther.getEstatus()!=null && this.getEstatus().equals(castOther.getEstatus()) ) )
 && (this.getCodareaest()==castOther.getCodareaest());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDescripcion() == null ? 0 : this.getDescripcion().hashCode() );
         result = 37 * result + ( getEstatus() == null ? 0 : this.getEstatus().hashCode() );
         result = 37 * result + this.getCodareaest();
         return result;
   }   


}


