package com.inverse.ing;
// Generated 09/05/2017 03:21:15 PM by Hibernate Tools 4.0.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Categoria generated by hbm2java
 */
@Entity
@Table(name="categoria"
    ,schema="public"
)
public class Categoria  implements java.io.Serializable {


     private CategoriaId id;

    public Categoria() {
    }

    public Categoria(CategoriaId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="nombre", column=@Column(name="nombre") ), 
        @AttributeOverride(name="descripcion", column=@Column(name="descripcion") ), 
        @AttributeOverride(name="estatus", column=@Column(name="estatus", length=1) ), 
        @AttributeOverride(name="codigo", column=@Column(name="codigo", nullable=false) ) } )
    public CategoriaId getId() {
        return this.id;
    }
    
    public void setId(CategoriaId id) {
        this.id = id;
    }




}


