package com.inverse.ing;
// Generated 09/05/2017 03:21:15 PM by Hibernate Tools 4.0.1.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CategoriaId generated by hbm2java
 */
@Embeddable
public class CategoriaId  implements java.io.Serializable {


     private String nombre;
     private String descripcion;
     private Character estatus;
     private int codigo;

    public CategoriaId() {
    }

	
    public CategoriaId(int codigo) {
        this.codigo = codigo;
    }
    public CategoriaId(String nombre, String descripcion, Character estatus, int codigo) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.estatus = estatus;
       this.codigo = codigo;
    }
   


    @Column(name="nombre")
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }


    @Column(name="descripcion")
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }


    @Column(name="estatus", length=1)
    public Character getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(Character estatus) {
        this.estatus = estatus;
    }


    @Column(name="codigo", nullable=false)
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CategoriaId) ) return false;
		 CategoriaId castOther = ( CategoriaId ) other; 
         
		 return ( (this.getNombre()==castOther.getNombre()) || ( this.getNombre()!=null && castOther.getNombre()!=null && this.getNombre().equals(castOther.getNombre()) ) )
 && ( (this.getDescripcion()==castOther.getDescripcion()) || ( this.getDescripcion()!=null && castOther.getDescripcion()!=null && this.getDescripcion().equals(castOther.getDescripcion()) ) )
 && ( (this.getEstatus()==castOther.getEstatus()) || ( this.getEstatus()!=null && castOther.getEstatus()!=null && this.getEstatus().equals(castOther.getEstatus()) ) )
 && (this.getCodigo()==castOther.getCodigo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNombre() == null ? 0 : this.getNombre().hashCode() );
         result = 37 * result + ( getDescripcion() == null ? 0 : this.getDescripcion().hashCode() );
         result = 37 * result + ( getEstatus() == null ? 0 : this.getEstatus().hashCode() );
         result = 37 * result + this.getCodigo();
         return result;
   }   


}


