package com.inverse.ing;
// Generated 09/05/2017 03:21:15 PM by Hibernate Tools 4.0.1.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EmpleadoId generated by hbm2java
 */
@Embeddable
public class EmpleadoId  implements java.io.Serializable {


     private String username;
     private String cargo;
     private String riforganizacion;
     private Character estatus;
     private Integer tipo;

    public EmpleadoId() {
    }

    public EmpleadoId(String username, String cargo, String riforganizacion, Character estatus, Integer tipo) {
       this.username = username;
       this.cargo = cargo;
       this.riforganizacion = riforganizacion;
       this.estatus = estatus;
       this.tipo = tipo;
    }
   


    @Column(name="username")
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }


    @Column(name="cargo")
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }


    @Column(name="riforganizacion")
    public String getRiforganizacion() {
        return this.riforganizacion;
    }
    
    public void setRiforganizacion(String riforganizacion) {
        this.riforganizacion = riforganizacion;
    }


    @Column(name="estatus", length=1)
    public Character getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(Character estatus) {
        this.estatus = estatus;
    }


    @Column(name="tipo")
    public Integer getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Integer tipo) {
        this.tipo = tipo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EmpleadoId) ) return false;
		 EmpleadoId castOther = ( EmpleadoId ) other; 
         
		 return ( (this.getUsername()==castOther.getUsername()) || ( this.getUsername()!=null && castOther.getUsername()!=null && this.getUsername().equals(castOther.getUsername()) ) )
 && ( (this.getCargo()==castOther.getCargo()) || ( this.getCargo()!=null && castOther.getCargo()!=null && this.getCargo().equals(castOther.getCargo()) ) )
 && ( (this.getRiforganizacion()==castOther.getRiforganizacion()) || ( this.getRiforganizacion()!=null && castOther.getRiforganizacion()!=null && this.getRiforganizacion().equals(castOther.getRiforganizacion()) ) )
 && ( (this.getEstatus()==castOther.getEstatus()) || ( this.getEstatus()!=null && castOther.getEstatus()!=null && this.getEstatus().equals(castOther.getEstatus()) ) )
 && ( (this.getTipo()==castOther.getTipo()) || ( this.getTipo()!=null && castOther.getTipo()!=null && this.getTipo().equals(castOther.getTipo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUsername() == null ? 0 : this.getUsername().hashCode() );
         result = 37 * result + ( getCargo() == null ? 0 : this.getCargo().hashCode() );
         result = 37 * result + ( getRiforganizacion() == null ? 0 : this.getRiforganizacion().hashCode() );
         result = 37 * result + ( getEstatus() == null ? 0 : this.getEstatus().hashCode() );
         result = 37 * result + ( getTipo() == null ? 0 : this.getTipo().hashCode() );
         return result;
   }   


}


