package com.inverse.ing;
// Generated 09/05/2017 03:21:15 PM by Hibernate Tools 4.0.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Evaluadoresdesafio generated by hbm2java
 */
@Entity
@Table(name="evaluadoresdesafio"
    ,schema="public"
)
public class Evaluadoresdesafio  implements java.io.Serializable {


     private EvaluadoresdesafioId id;

    public Evaluadoresdesafio() {
    }

    public Evaluadoresdesafio(EvaluadoresdesafioId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="evaluador", column=@Column(name="evaluador") ), 
        @AttributeOverride(name="iddesafio", column=@Column(name="iddesafio") ) } )
    public EvaluadoresdesafioId getId() {
        return this.id;
    }
    
    public void setId(EvaluadoresdesafioId id) {
        this.id = id;
    }




}


