package com.inverse.ing;
// Generated 09/05/2017 03:21:15 PM by Hibernate Tools 4.0.1.Final


import java.util.Arrays;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IdeaId generated by hbm2java
 */
@Embeddable
public class IdeaId  implements java.io.Serializable {


     private String titulo;
     private String descripcion;
     private Integer cantidadvotos;
     private String autor;
     private Character estatus;
     private int codigo;
     private Integer coddesafio;
     private byte[] urlImagen;

    public IdeaId() {
    }

	
    public IdeaId(int codigo) {
        this.codigo = codigo;
    }
    public IdeaId(String titulo, String descripcion, Integer cantidadvotos, String autor, Character estatus, int codigo, Integer coddesafio, byte[] urlImagen) {
       this.titulo = titulo;
       this.descripcion = descripcion;
       this.cantidadvotos = cantidadvotos;
       this.autor = autor;
       this.estatus = estatus;
       this.codigo = codigo;
       this.coddesafio = coddesafio;
       this.urlImagen = urlImagen;
    }
   


    @Column(name="titulo")
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }


    @Column(name="descripcion")
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }


    @Column(name="cantidadvotos")
    public Integer getCantidadvotos() {
        return this.cantidadvotos;
    }
    
    public void setCantidadvotos(Integer cantidadvotos) {
        this.cantidadvotos = cantidadvotos;
    }


    @Column(name="autor")
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }


    @Column(name="estatus", length=1)
    public Character getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(Character estatus) {
        this.estatus = estatus;
    }


    @Column(name="codigo", nullable=false)
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }


    @Column(name="coddesafio")
    public Integer getCoddesafio() {
        return this.coddesafio;
    }
    
    public void setCoddesafio(Integer coddesafio) {
        this.coddesafio = coddesafio;
    }


    @Column(name="url_imagen")
    public byte[] getUrlImagen() {
        return this.urlImagen;
    }
    
    public void setUrlImagen(byte[] urlImagen) {
        this.urlImagen = urlImagen;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IdeaId) ) return false;
		 IdeaId castOther = ( IdeaId ) other; 
         
		 return ( (this.getTitulo()==castOther.getTitulo()) || ( this.getTitulo()!=null && castOther.getTitulo()!=null && this.getTitulo().equals(castOther.getTitulo()) ) )
 && ( (this.getDescripcion()==castOther.getDescripcion()) || ( this.getDescripcion()!=null && castOther.getDescripcion()!=null && this.getDescripcion().equals(castOther.getDescripcion()) ) )
 && ( (this.getCantidadvotos()==castOther.getCantidadvotos()) || ( this.getCantidadvotos()!=null && castOther.getCantidadvotos()!=null && this.getCantidadvotos().equals(castOther.getCantidadvotos()) ) )
 && ( (this.getAutor()==castOther.getAutor()) || ( this.getAutor()!=null && castOther.getAutor()!=null && this.getAutor().equals(castOther.getAutor()) ) )
 && ( (this.getEstatus()==castOther.getEstatus()) || ( this.getEstatus()!=null && castOther.getEstatus()!=null && this.getEstatus().equals(castOther.getEstatus()) ) )
 && (this.getCodigo()==castOther.getCodigo())
 && ( (this.getCoddesafio()==castOther.getCoddesafio()) || ( this.getCoddesafio()!=null && castOther.getCoddesafio()!=null && this.getCoddesafio().equals(castOther.getCoddesafio()) ) )
 && ( (this.getUrlImagen()==castOther.getUrlImagen()) || ( this.getUrlImagen()!=null && castOther.getUrlImagen()!=null && Arrays.equals(this.getUrlImagen(), castOther.getUrlImagen()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTitulo() == null ? 0 : this.getTitulo().hashCode() );
         result = 37 * result + ( getDescripcion() == null ? 0 : this.getDescripcion().hashCode() );
         result = 37 * result + ( getCantidadvotos() == null ? 0 : this.getCantidadvotos().hashCode() );
         result = 37 * result + ( getAutor() == null ? 0 : this.getAutor().hashCode() );
         result = 37 * result + ( getEstatus() == null ? 0 : this.getEstatus().hashCode() );
         result = 37 * result + this.getCodigo();
         result = 37 * result + ( getCoddesafio() == null ? 0 : this.getCoddesafio().hashCode() );
         int urlImagenHashcode = 0;
         byte[] urlImagenProperty = this.getUrlImagen();
         if(urlImagenProperty != null) {
             urlImagenHashcode = 1;
             for (int i=0; i<urlImagenProperty.length; i++) {
                 urlImagenHashcode = 37 * urlImagenHashcode + urlImagenProperty[i];
             }
         }

         result = 37 * result + urlImagenHashcode;

         return result;
   }   


}


