package com.inverse.ing;
// Generated 09/05/2017 03:21:15 PM by Hibernate Tools 4.0.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Idea generated by hbm2java
 */
@Entity
@Table(name="idea"
    ,schema="public"
)
public class Idea  implements java.io.Serializable {


     private IdeaId id;

    public Idea() {
    }

    public Idea(IdeaId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="titulo", column=@Column(name="titulo") ), 
        @AttributeOverride(name="descripcion", column=@Column(name="descripcion") ), 
        @AttributeOverride(name="cantidadvotos", column=@Column(name="cantidadvotos") ), 
        @AttributeOverride(name="autor", column=@Column(name="autor") ), 
        @AttributeOverride(name="estatus", column=@Column(name="estatus", length=1) ), 
        @AttributeOverride(name="codigo", column=@Column(name="codigo", nullable=false) ), 
        @AttributeOverride(name="coddesafio", column=@Column(name="coddesafio") ), 
        @AttributeOverride(name="urlImagen", column=@Column(name="url_imagen") ) } )
    public IdeaId getId() {
        return this.id;
    }
    
    public void setId(IdeaId id) {
        this.id = id;
    }




}


