package com.inverse.ing;
// Generated 09/05/2017 03:21:15 PM by Hibernate Tools 4.0.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Organizacion generated by hbm2java
 */
@Entity
@Table(name="organizacion"
    ,schema="public"
)
public class Organizacion  implements java.io.Serializable {


     private OrganizacionId id;

    public Organizacion() {
    }

    public Organizacion(OrganizacionId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="rif", column=@Column(name="rif") ), 
        @AttributeOverride(name="razonsocial", column=@Column(name="razonsocial") ), 
        @AttributeOverride(name="direccion", column=@Column(name="direccion") ), 
        @AttributeOverride(name="telefono", column=@Column(name="telefono") ), 
        @AttributeOverride(name="sucursal", column=@Column(name="sucursal") ), 
        @AttributeOverride(name="rifmatriz", column=@Column(name="rifmatriz") ), 
        @AttributeOverride(name="nombre", column=@Column(name="nombre") ) } )
    public OrganizacionId getId() {
        return this.id;
    }
    
    public void setId(OrganizacionId id) {
        this.id = id;
    }




}


