package com.inverse.ing;
// Generated 09/05/2017 03:21:15 PM by Hibernate Tools 4.0.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Perfil generated by hbm2java
 */
@Entity
@Table(name="perfil"
    ,schema="public"
)
public class Perfil  implements java.io.Serializable {


     private PerfilId id;

    public Perfil() {
    }

    public Perfil(PerfilId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="username", column=@Column(name="username") ), 
        @AttributeOverride(name="nombre", column=@Column(name="nombre") ), 
        @AttributeOverride(name="apellido", column=@Column(name="apellido") ), 
        @AttributeOverride(name="telefono", column=@Column(name="telefono") ), 
        @AttributeOverride(name="estatus", column=@Column(name="estatus", length=1) ), 
        @AttributeOverride(name="direccion", column=@Column(name="direccion") ), 
        @AttributeOverride(name="genero", column=@Column(name="genero") ), 
        @AttributeOverride(name="fechanacimiento", column=@Column(name="fechanacimiento", length=13) ) } )
    public PerfilId getId() {
        return this.id;
    }
    
    public void setId(PerfilId id) {
        this.id = id;
    }




}


