package com.inverse.ing;
// Generated 09/05/2017 03:21:15 PM by Hibernate Tools 4.0.1.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsuarioId generated by hbm2java
 */
@Embeddable
public class UsuarioId  implements java.io.Serializable {


     private String username;
     private String email;
     private String pass;
     private Integer rol;
     private String avatar;
     private String estatus;

    public UsuarioId() {
    }

    public UsuarioId(String username, String email, String pass, Integer rol, String avatar, String estatus) {
       this.username = username;
       this.email = email;
       this.pass = pass;
       this.rol = rol;
       this.avatar = avatar;
       this.estatus = estatus;
    }
   


    @Column(name="username")
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }


    @Column(name="email")
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }


    @Column(name="pass")
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }


    @Column(name="rol")
    public Integer getRol() {
        return this.rol;
    }
    
    public void setRol(Integer rol) {
        this.rol = rol;
    }


    @Column(name="avatar")
    public String getAvatar() {
        return this.avatar;
    }
    
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }


    @Column(name="estatus", length=1)
    public String getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsuarioId) ) return false;
		 UsuarioId castOther = ( UsuarioId ) other; 
         
		 return ( (this.getUsername()==castOther.getUsername()) || ( this.getUsername()!=null && castOther.getUsername()!=null && this.getUsername().equals(castOther.getUsername()) ) )
 && ( (this.getEmail()==castOther.getEmail()) || ( this.getEmail()!=null && castOther.getEmail()!=null && this.getEmail().equals(castOther.getEmail()) ) )
 && ( (this.getPass()==castOther.getPass()) || ( this.getPass()!=null && castOther.getPass()!=null && this.getPass().equals(castOther.getPass()) ) )
 && ( (this.getRol()==castOther.getRol()) || ( this.getRol()!=null && castOther.getRol()!=null && this.getRol().equals(castOther.getRol()) ) )
 && ( (this.getAvatar()==castOther.getAvatar()) || ( this.getAvatar()!=null && castOther.getAvatar()!=null && this.getAvatar().equals(castOther.getAvatar()) ) )
 && ( (this.getEstatus()==castOther.getEstatus()) || ( this.getEstatus()!=null && castOther.getEstatus()!=null && this.getEstatus().equals(castOther.getEstatus()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUsername() == null ? 0 : this.getUsername().hashCode() );
         result = 37 * result + ( getEmail() == null ? 0 : this.getEmail().hashCode() );
         result = 37 * result + ( getPass() == null ? 0 : this.getPass().hashCode() );
         result = 37 * result + ( getRol() == null ? 0 : this.getRol().hashCode() );
         result = 37 * result + ( getAvatar() == null ? 0 : this.getAvatar().hashCode() );
         result = 37 * result + ( getEstatus() == null ? 0 : this.getEstatus().hashCode() );
         return result;
   }   


}


